@startuml
skinparam classAttributeIconSize 0

package src{
    package model{
        package enums{
            enum Couleur{
                ..Values..
                ABSENT
                BLEU
                JAUNE
                ROUGE
                VERT
                ORANGE
                VIOLET
                TURQUOISE
                ROSE
                ..Mehtods..
                + getVraiesCouleurs() : Couleur[] {static}
            }
            enum Indice{
                ..Values..
                Bien_PLACE
                MAL_PLACE
                ABSENT
            }
        }
        class Combinaison{
            ..Fields..
            - tailleCombi : Integer
            ..Methods..
            + <<create>> Combinaison(tailleCombi : Integer)
            + genererCombinaison(taille : Integer) : Combinaison {static}
            + getCombinaison() : Couleur[]
            + setCouleur(index : Integer, couleur : Couleur)
            + getTailleCombinaison() : Integer
            + estComplet() : Boolean
        }
        class Joueur{
            ..Fields..
            - nom : String
            - score : Integer[]
            ..Methods..
            + <<create>> Joueur(nom : String)
            + getNom() : String
            + getScores() : Integer[]
            + ajouterScorePartie(score : Integer)
        }
        class LigneIndice{
            ..Fields..
            - tailleCombi : Integer
            ..Methods..
            + <<create>> LigneIndice(tailleCombi : Integer)
            + getTailleCombinaison() : Integer
            + getIntIndices() : Integer[]
            + getIndices() : Indice[]
            + calculerScore() : Integer
        }
        class Manche{
            ..Fields..
            - tentativeActuelle : Integer
            - nbTentatives : Integer
            ..Methods..
            + <<create>> Manche(tailleCombi : Integer, nbTentatives : Integer, modeJeu : ModeJeu)
            + ajouterObservateurManche(observateur : ObservateurManche[])
            + ajouterObservateurTentative(observateur : ObservateurTentative[])
            + jouerManche()
            + calculerScore() : Integer
            + getCombinaisonSecrete() : Combinaison
            + getNbTentative() : Integer
            + getTentativeActuelle() : Integer
            + GetTentatives() : Tentative[]
        }
        interface ModeJeu <<interface>>{
            ..Methods..
            afficherIndices(ligne : LigneIndice)
        }
        class Partie{
            ..Fields..
            - score : Integer
            ..Methods..
            + <<create>> Partie()
            + ajouterObservateurPartie(observateur : ObservateurPartie[])
            + ajouterObservateurManche(observateur : ObservateurManche[])
            + ajouterObservateurTentative(observateur : ObservateurTentative[])
            + lancerPartie()
            + getManches() : Manche[]
            + finirPartie()
        }
        class Tentative{
            ..Methods..
            + <<create>> Tentative(taille : Integer, modeJeu : ModeJeu)
            + ajouterObservateurTentative(observateur : ObservateurTentative[])
            + lancerTentative()
            + ajoutCouleur(index : Integer, couleur : Couleur)
            + evaluerTentative(combinaisonSecrete : Combinaison) : Boolean
            + getCombinaisonEntree() : Combinaison
            + getLigneIndice() : LigneIndice
            + calculBonus() : Integer
            + calculerScore() : Integer
        }
        interface ObservateurPartie <<interface>>{
            ..Methods..
            + setPartie(partie : Partie)
            + creerJoueur() : Joueur
            + deciderNbManches() : Integer
            + deciderTailleCombinaison() : Integer
            + deciderNbTentatives() : Integer
            + deciderModeJeu() : ModeJeu
        }
        interface ObservateurManche <<interface>>{
            ..Methods..
            + miseEnPlacePlateau()
            + setManche(manche : Manche)
            + demanderValidationTentative() : Boolean
        }
        interface ObservateurTentative <<interface>>{
            ..Methods..
            + setTentative(tentative : Tentative)
            + changerCouleur(combinaison : Combinaison)
            + afficherIndices(indices : LigneIndice)
            + affichageTentative(combinaison : Combinaison)
        }
    }
    package view{
        class Classique{
            ..Methods..
            afficherIndices(ligne : LigneIndice)
        }
        class Facile{
            ..Methods..
            afficherIndices(ligne : LigneIndice)
        }
        class Numerique{
            ..Methods..
            afficherIndices(ligne : LigneIndice)
        }
        class AffichageFenetre{
            ..Fields..
            - fenetre : JFrame
            ..Methods..
            + <<create>> AffichageFenetre(gestionnaire : GestionnaireJeu)
            ..Partie..
            + setPartie(partie : Partie)
            + creerJoueur() : Joueur
            + deciderNbManches() : Integer
            + deciderTailleCombinaison() : Integer
            + deciderNbTentatives() : Integer
            + deciderModeJeu() : ModeJeu
            ..Manche..
            + miseEnPlacePlateau()
            + setManche(manche : Manche)
            + demanderValidationTentative() : Boolean
            ..Tentative..
            + setTentative(tentative : Tentative)
            + changerCouleur(combinaison : Combinaison)
            + afficherIndices(indices : LigneIndice)
            + affichageTentative(combinaison : Combinaison)
        }
        class AffichageConsole{
            ..Fields..
            - in : Scanner {static}
            ..Methods..
            + <<create>> AffichageFenetre(gestionnaire : GestionnaireJeu)
            ..Partie..
            + setPartie(partie : Partie)
            + creerJoueur() : Joueur
            + deciderNbManches() : Integer
            + deciderTailleCombinaison() : Integer
            + deciderNbTentatives() : Integer
            + deciderModeJeu() : ModeJeu
            ..Manche..
            + miseEnPlacePlateau()
            + setManche(manche : Manche)
            + demanderValidationTentative() : Boolean
            ..Tentative..
            + setTentative(tentative : Tentative)
            + changerCouleur(combinaison : Combinaison)
            + afficherIndices(indices : LigneIndice)
            + affichageTentative(combinaison : Combinaison)
        }
    }
    package controller{
        class GestionnaireJeu{
            ..Methods..
            + demarrerPartie()
        }
    }
}

src.controller.GestionnaireJeu ..> src.model.Partie : <<utilises>>


src.model.Combinaison "1" o--> "4..6\n- combinaison" src.model.enums.Couleur

src.model.LigneIndice "1" o--> "4..6\n- indices" src.model.enums.Indice

src.model.Manche "1" o--> "10..12\n- tentatives" src.model.Tentative
src.model.Manche "1" o--> "1\n- combinaison" src.model.Combinaison
src.model.Manche "1" o-> "1\n- observateur" src.model.ObservateurManche

src.model.ModeJeu ...> src.model.LigneIndice : <<utilises>>
src.model.ModeJeu <|.. src.view.Classique
src.model.ModeJeu <|.. src.view.Facile
src.model.ModeJeu <|.. src.view.Numerique

src.model.Partie "1" o-> "1\n- joueur" src.model.Joueur
src.model.Partie "1" o--> "3..5\n- manches" src.model.Manche
src.model.Partie "1" o-> "1\n- observateur" src.model.ObservateurPartie
src.model.Partie .> src.model.ModeJeu : <<uses>>

src.model.Tentative "1" o--> "1\n- combinaisonEntree" src.model.Combinaison
src.model.Tentative "1" o--> "1\n- ligneIndice" src.model.LigneIndice
src.model.Tentative "1" o-> "1\n- modeJeu" src.model.ModeJeu
src.model.Tentative "1" o-> "1\n- observateur" src.model.ObservateurTentative

src.view.Classique ..> src.model.LigneIndice : <<utilises>>

src.view.Facile ..> src.model.LigneIndice : <<utilises>>

src.view.Numerique ..> src.model.LigneIndice : <<utilises>>

src.view.AffichageConsole ..|> src.model.ObservateurPartie
src.view.AffichageConsole ..|> src.model.ObservateurManche
src.view.AffichageConsole ..|> src.model.ObservateurTentative

src.model.ObservateurPartie <|.. src.view.AffichageFenetre
src.model.ObservateurManche <|.. src.view.AffichageFenetre
src.model.ObservateurTentative <|.. src.view.AffichageFenetre

@enduml